---

# docker-compose version 1.21.0

version: '3'

services:
  nginx:
    image: 'datadog/docker-library:nginx-vts'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-size: "${LOGGING_MAX_SIZE}"
        max-file: "${LOGGING_MAX_FILE}"
    ports:
        - "${SERVICE_LISTEN_IP_ADDRESS}:80:80"
        - "${SERVICE_LISTEN_IP_ADDRESS}:443:443"
    volumes:
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './config/nginx/ssl:/etc/nginx/ssl:ro' # Only used for self-signed
      - '/etc/ssl/:/etc/ssl/:ro'
      - '/etc/pki/:/etc/pki/:ro'
    networks:
      - 'nginx_proxy'
      - 'services'

  nginx_vts_exporter:
    image: 'sophos/nginx-vts-exporter:v0.10.3'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-size: "${LOGGING_MAX_SIZE}"
        max-file: "${LOGGING_MAX_FILE}"
    ports:
      - "${EXPORTER_LISTEN_IP_ADDRESS}:9913:9913"
    environment:
      NGINX_STATUS: 'http://nginx/status/json'
    networks:
      - 'nginx_proxy'

networks:
  nginx_proxy: {}
  services:
    external:
      name: 'services'
